# name: Generate Podcast Feeds
# on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v3
#       - name: Python Setup
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.9'

#       - name: Run Feed Generator
#         uses: planetoftheweb/podcast-generator@main

